### ISSUE TITLE
Basic default face is not correct in tty mode

### ISSUE THREAD

**Issue by zrquan** [catppuccin/emacs#175] opened 2024-08-09 06:34 UTC
If I start an emacs process first and then open a frame using `emacsclient -nw`, the background color isn't set correctly.

![image](https://github.com/user-attachments/assets/b922ecc2-7684-4a85-aaf5-117f3b39ed2f)

**Comment by jtbx** [comment] 2024-08-09 06:39
Hi,

Thanks for the report but this is a duplicate of #150, which I am
yet to look into. If you have any clue why this occurs that would
be awesome.

**Closed by jtbx** 2024-08-09 06:39 UTC
